zsh: functions: Make sure kreboot works with kernel-modules-hook
Signed-off-by: Zile995 <stefan.zivkovic995@gmail.com>

diff --git a/zsh/functions/kreboot b/zsh/functions/kreboot
--- a/zsh/functions/kreboot
+++ b/zsh/functions/kreboot
@@ -6,22 +6,23 @@ kreboot() {
   # set pkgbase
   local pkgbase="$1"
   [[ -z "$1" ]] && \
-    pkgbase=$('find' /usr/lib/modules/$('uname' -r) \
+    pkgbase=$(find /usr/lib/modules/$(uname -r) \
       -mindepth 1 -maxdepth 1 \
       ! -path '*/\.*' ! -path '*/build' -type d \
-      -exec 'pacman' -Qqo {} \;)
-  [[ -z "$pkgbase" ]] && echo "Unable to find kernel modules" && return 1
+      -exec sh -c \
+      'if ! pacman -Qqo "$(dirname $0)/pkgbase" > /dev/null 2>&1; then [[ -e "$(dirname $0)/pkgbase" && "$(basename $(dirname $0))" = "$(uname -r)" ]] && cat "$(dirname $0)/pkgbase"; else pacman -Qqo $0; fi;' {} \;)
+  [[ -z "$pkgbase" ]] && echo "Unable to find valid modules of the currently running $(uname -r) kernel." && return 1
 
   # vmlinuz path
   local vmlinuz
   vmlinuz="/boot/vmlinuz-${pkgbase}"
-  [[ ! -e "$vmlinuz" ]] && echo "Unable to find compressed kernel image, vmlinuz-${pkgbase}" && return 1
+  [[ ! -e "$vmlinuz" ]] && echo "Unable to find compressed kernel image, vmlinuz-${pkgbase}." && return 1
 
   # initramfs path
   local initramfs="/boot/booster-${pkgbase}.img"
   [[ ! -e "$initramfs" ]] && initramfs="/boot/initramfs-${pkgbase}.img"
-  [[ ! -e "$initramfs" ]] && echo "Unable to find initial ramdisk for ${pkgbase} kernel" && return 1
+  [[ ! -e "$initramfs" ]] && echo "Unable to find initial ramdisk for ${pkgbase} kernel." && return 1
 
-  sudo 'kexec' -l "${vmlinuz}" --initrd="${initramfs}" --reuse-cmdline
+  sudo kexec -l "${vmlinuz}" --initrd="${initramfs}" --reuse-cmdline
   systemctl kexec
 }
